# Generated by Django 4.2.17 on 2025-03-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo')),
                ('mdw', models.FloatField(blank=True, null=True, verbose_name='mdw')),
                ('latw', models.FloatField(blank=True, null=True, verbose_name='latw')),
                ('tmcw', models.FloatField(blank=True, null=True, verbose_name='tmcw')),
                ('racw', models.FloatField(blank=True, null=True, verbose_name='racw')),
                ('araw', models.FloatField(blank=True, null=True, verbose_name='araw')),
                ('mcw', models.FloatField(blank=True, null=True, verbose_name='mcw')),
                ('psdsw', models.FloatField(blank=True, null=True, verbose_name='psdsw')),
                ('s6w', models.FloatField(blank=True, null=True, verbose_name='s6w')),
                ('mdr', models.FloatField(blank=True, null=True, verbose_name='mdr')),
                ('latr', models.FloatField(blank=True, null=True, verbose_name='latr')),
                ('tmcr', models.FloatField(blank=True, null=True, verbose_name='tmcr')),
                ('racr', models.FloatField(blank=True, null=True, verbose_name='racr')),
                ('arar', models.FloatField(blank=True, null=True, verbose_name='arar')),
                ('mcr', models.FloatField(blank=True, null=True, verbose_name='mcr')),
                ('psdsr', models.FloatField(blank=True, null=True, verbose_name='psdsr')),
                ('s6r', models.FloatField(blank=True, null=True, verbose_name='s6r')),
                ('mdg', models.FloatField(blank=True, null=True, verbose_name='mdg')),
                ('latg', models.FloatField(blank=True, null=True, verbose_name='latg')),
                ('tmcg', models.FloatField(blank=True, null=True, verbose_name='tmcg')),
                ('racg', models.FloatField(blank=True, null=True, verbose_name='racg')),
                ('arag', models.FloatField(blank=True, null=True, verbose_name='arag')),
                ('mcg', models.FloatField(blank=True, null=True, verbose_name='mcg')),
                ('psdsg', models.FloatField(blank=True, null=True, verbose_name='psdsg')),
                ('s6g', models.FloatField(blank=True, null=True, verbose_name='s6g')),
                ('mdwb', models.FloatField(blank=True, null=True, verbose_name='mdwb')),
                ('latb', models.FloatField(blank=True, null=True, verbose_name='latb')),
                ('tmcb', models.FloatField(blank=True, null=True, verbose_name='tmcb')),
                ('racb', models.FloatField(blank=True, null=True, verbose_name='racb')),
                ('arab', models.FloatField(blank=True, null=True, verbose_name='arab')),
                ('mcb', models.FloatField(blank=True, null=True, verbose_name='mcb')),
                ('psdsb', models.FloatField(blank=True, null=True, verbose_name='psdsb')),
                ('s6b', models.FloatField(blank=True, null=True, verbose_name='s6b')),
            ],
            options={
                'ordering': ['grupo'],
            },
        ),
    ]
