# Generated by Django 4.2.17 on 2025-03-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosModelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo')),
                ('feature1', models.FloatField(blank=True, null=True, verbose_name='Feature 1')),
                ('feature2', models.FloatField(blank=True, null=True, verbose_name='Feature 2')),
                ('feature3', models.FloatField(blank=True, null=True, verbose_name='Feature 3')),
                ('target', models.CharField(blank=True, max_length=50, null=True, verbose_name='Target')),
            ],
            options={
                'ordering': ['grupo'],
            },
        ),
    ]
