# Generated by Django 4.2.17 on 2025-01-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo01', '0003_alter_pessoa_options_pessoa_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descricao')),
                ('cid', models.CharField(max_length=20, verbose_name='CID')),
                ('valor', models.FloatField(blank=True, default=None, null=True, verbose_name='Valor')),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
    ]
